#pragma once

// TEST-ONLY STUB.
//
// In a real build this header is generated by Nitrogen from the TypeScript
// union `type LrcMode = "stx" | "std" | "noext" | "stx_noext"` (see
// package/src/types/client.ts). The unit tests compile the pure-logic C++
// units (Lrc, PacketCodec, Ecr17Protocol) in isolation, without running
// Nitrogen, so we provide a minimal enum that mirrors the generated one.
//
// The member names MUST match what the production code references
// (Lrc.cpp uses LrcMode::STX, LrcMode::STX_NOEXT, LrcMode::NOEXT). If Nitrogen
// turns out to emit different casing, that is a real bug to reconcile when the
// codegen is run — this stub documents the contract the code assumes today.

namespace margelo::nitro::ecr17 {

enum class LrcMode {
    STX,
    STD,
    NOEXT,
    STX_NOEXT,
};

}  // namespace margelo::nitro::ecr17
